# 1_BUIDING BASIC FUNCTION WITH NUMPY
Numpy is the main package for scientific computing in Python.It is maintained by a large community.

1.1-sigmoid function, np.exp()

In [1]:
import numpy as np

def sigmoid(x):
    '''Compute the sigmoid of x'''
    s=1/(np.exp(-x)+1)
    return s
x=np.array([1,2,3])
print(sigmoid(x))

[0.73105858 0.88079708 0.95257413]


1.2-Sigmoid gradient

sigmoid_derivative(x)=$$\sigma'(x)=\sigma(x)(1-\sigma(x))$$

In [2]:
# GRADED FUNCTION: sigmoid_derivative

def sigmoid_derivative(x):
    """
    Compute the gradient (also called the slope or derivative) of the sigmoid function with respect to its input x.
    You can store the output of the sigmoid function into variables and then use it to calculate the gradient.
    
    Arguments:
    x -- A scalar or numpy array

    Return:
    ds -- Your computed gradient.
    """
    
    ### START CODE HERE ### (≈ 2 lines of code)
    s = sigmoid(x)
    ds = s*(1-s)
    ### END CODE HERE ###
    
    return ds
x = np.array([1, 2, 3])
print ("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)))

sigmoid_derivative(x) = [0.19661193 0.10499359 0.04517666]


1.3-Reshaping array

Two common numpy functions in deep learning are np.shape and np.reshape()
+) X. shape is used to get the shape(dimension) of a matrix/vector X.
+) X.reshape() is used to reshape X into some other dimension.

For example, in computer science, an image is represented by a 3D array of shape(length,height,depth=3). However, when you read an image as the input of an algorithm you convert it to the vector of shape(length*height*3,1). In other words, you "unroll", or reshape, the 3D array into a 1D vector.


Now we have exercise: Implement image2vector() that takes an input of shape(length,height,3) and returns a vector of shape (length*height*3,1). For example, if you would like to reshape an array v of shape(a,b,c) into a vector of shape(a*b,c) you would do:


v = v.reshape((v.shape[0]*v.shape[1], v.shape[2])) 

Now come to the code.

In [2]:
import numpy as np
def image2vector(image):
    """
    Argument:
    image-- a numpy array of shape

    Returns:
    v-a vector of shape
        """
    v=image.reshape(image.shape[0]*image.shape[1]*image.shape[2],1)

    return v

image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])
print ("image2vector(image) = " + str(image2vector(image)))


image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


1.4- Normalizing rows

Another common technique we use in Machine Learning and Deep Learning is to normalize our data. It often leads to a better performance because gradient descent converges faster after normalization. Here, by normalization we mean changing x to x/||x||(diving each row vector of x by it norms)

||x||=np.linalg.norm(x,axis=1,keepdims=True)


In [3]:
def normalizeRows(x):
    x_norm=np.linalg.norm(x,axis=1,keepdims=True)

    #Divide x by its norm
    x=x/x_norm

    return x
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))


normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


1.5-Broadcasting and the softmax function
A very important concept to understand in numpy is broadcasting. It is very useful for performing mathematical operations betweens arrays of different shapes. 
A softmax function is a mathematical function that converts a vector of real numbers into a probability distribution. It exponentiates each component, making them positive, and then normalizes them by dividing by the sum of all exponentiated values.

In [4]:
def softmax(x):
    #Apply exp() element-wise to x. Use np.exp(...)
    x_exp=np.exp(x)

    #Create a vector x_sum that sums each row of x_exp
    x_sum=np.sum(x_exp,axis=1,keepdims=True)

    #Compute softmax(x)
    s=x_exp/x_sum

    return s

In [5]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


# 2. Vectorization


In deep learning, you deal with very large datasets. Hence, a non-computationally-optimal function can become a huge bottleneck in your algorithm and can result in a model that takes ages to run. To make sure that your code is computationally efficient, you will use vectorization. For example, try to tell the difference between the following implementations.

In [6]:
import time 

x1=[9,2,5,0,0,7,5,0,0,0,9,2,5,0,0]
x2=[9,2,2,9,0,9,2,5,0,0,9,2,5,0,0]

### CLASSIC DOT PRODUCT OF VECTOR ###
tic=time.process_time()
dot=0
for i in range(len(x1)):
    dot+=x1[i]*x2[i]
toc=time.process_time()
print("dot= " +str(dot)+ "\n-----Computation time= " +str(1000*(toc-tic)) +"ms")
### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j]*x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")


dot= 278
-----Computation time= 0.0ms
elementwise multiplication = [81.  4. 10.  0.  0. 63. 10.  0.  0.  0. 81.  4. 25.  0.  0.]
 ----- Computation time = 0.0ms
gdot = [21.56688229 19.6650908  18.25380761]
 ----- Computation time = 0.0ms


In [7]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.0ms
outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Computation time = 0.0ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.0ms
gdot = [21.56688229 19.6650908  18.25380761]
 ----- Computation time = 0.0ms


2.1 -Implement the L1 and L2 loss function

In [8]:
def L1(yhat,y):
    #yhat-- vetor of size m(predicted labels)
    #y-vector of size m (true labels)

    loss=sum(abs(yhat-y))
    return loss
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


In [9]:
def L2(yhat,y):
    x=yhat-y
    loss=np.dot(x,x)
    return loss
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))


L2 = 0.43
